repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
      
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: ^src/
        types: [python]
        args: [--strict]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Optional pytest hook (disabled by default, can be enabled manually)
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
        stages: [manual]
        args: [-q]