# NFL GPP SimLab Configuration File
# This file configures simulation parameters for the Monte Carlo engine

# Simulation parameters
n_trials = 10000        # Number of Monte Carlo trials
base_seed = 42          # Random seed for reproducibility  
n_jobs = 1              # Number of parallel jobs (or set NFL_GPP_SIMLAB_N_JOBS env var)

# Statistical quantiles to compute (0-1 range)
quantiles = [0.1, 0.25, 0.5, 0.75, 0.9, 0.95]

# Advanced options (optional)
# These are placeholders for future functionality
[advanced]
enable_boom_analysis = true
enable_value_metrics = true
coverage_threshold = 0.8
