name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install '.[dev]'
      - name: Lint
        run: |
          ruff --version
          ruff check .
      - name: Type check
        run: mypy src
      - name: Test (with coverage)
        run: pytest -q --cov=nfl_gpp_simlab --cov-report=term-missing --cov-report=xml
      - name: Coverage summary
        run: |
          python - <<'PY'
          import xml.etree.ElementTree as ET
          import os
          tree = ET.parse('coverage.xml')
          root = tree.getroot()
          line_rate = float(root.get('line-rate', 0.0))
          percent = round(line_rate * 100, 1)
          summary = f"Coverage: {percent}% lines covered"
          with open(os.environ.get('GITHUB_STEP_SUMMARY', 'summary.md'), 'a', encoding='utf-8') as f:
              f.write(summary + '\n')
          print(summary)
          PY
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
          if-no-files-found: ignore