name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pre-commit
        run: |
          pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing

      - name: Quickstart smoke test
        if: matrix.python-version == '3.11'
        run: |
          python examples/quickstart.py

      - name: Soft coverage gate
        if: matrix.python-version == '3.11'
        run: |
          coverage_percent=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(f\"{float(root.attrib['line-rate']) * 100:.1f}\")")
          echo "Coverage: ${coverage_percent}%"
          if (( $(echo "$coverage_percent < 80" | bc -l) )); then
            echo "⚠️  WARNING: Coverage is below 80% threshold (${coverage_percent}%)"
            echo "This is a soft gate - the build continues but consider adding tests."
          else
            echo "✅ Coverage meets 80% threshold (${coverage_percent}%)"
          fi

      - name: Coverage summary
        if: matrix.python-version == '3.11'
        run: |
          coverage_percent=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(f\"{float(root.attrib['line-rate']) * 100:.1f}\")")
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "Coverage: ${coverage_percent}%" >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage to artifacts
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
